# Generated by Django 5.0.2 on 2024-03-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
