# Generated by Django 5.0.2 on 2024-03-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizevariant',
            name='price',
        ),
    ]
